export const collections = {
  amcPlans: "amcPlans",
  applications: "applications",
  auditLogs: "auditLogs",
  blogPosts: "blogPosts",
  careers: "careers",
  categories: "categories",
  clients: "clients",
  clientMembers: "clientMembers",
  complianceRecords: "complianceRecords",
  documents: "documents",
  emailLogs: "emailLogs",
  faqs: "faqs",
  inquiries: "inquiries",
  inspectionReports: "inspectionReports",
  invoices: "invoices",
  newsletterSubscriptions: "newsletterSubscriptions",
  notifications: "notifications",
  otpTokens: "otpTokens",
  passwordResetTokens: "passwordResetTokens",
  projects: "projects",
  rateLimitEvents: "rateLimitEvents",
  seoMetadata: "seoMetadata",
  services: "services",
  settings: "settings",
  supportTickets: "supportTickets",
  testimonials: "testimonials",
  uploadAssets: "uploadAssets",
  users: "users",
} as const;

export type CollectionName = (typeof collections)[keyof typeof collections];
